server:
  port: 8080

spring:
  cache:
    type: redis # choosing redis as catch contener

  redis:
    port: 6379
    host: localhost
    password: root

#    client-type: jedis   #if there are both of them then we need to mention here which to use

#config for lettuce
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: -1ms



#config for jedis [ don't forget to exclude from pom
#    jedis:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 0
#        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_cach?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
