server:
  port: 8080

spring:
  redis:
    port: 6379
    host: localhost
    password: root

#    client-type: jedis   #if there are both of them then we need to mention here which to use


#config for lettuce
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: -1ms


#config for jedis [ don't forget to exclude from pom
#    jedis:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 0
#        max-wait: -1ms


  # 连接池最大连接数（使用负值表示没有限制）

  # 连接池中的最大空闲连接

  # 连接池中的最小空闲连接

  # 连接池最大阻塞等待时间（使用负值表示没有限制）

  #指定客户端

